### ISSUE TITLE
Is it possible to hide quick-explorer's address bar from the lower left?

### ISSUE THREAD

**Issue by HelloMugen** [pjeby/quick-explorer#102]
Hello PJ, I have been installing this plugin since I started using OB very early. It is a very convenient and efficient plugin.

Recently I noticed that the new version displays quick-explorer's address bar in the lower leftAt the same time, the top address bar can also be used normally
Which seems redundant. Because I often pay attention to the sidebar, this change seems to visually destroy the “ left-center-right ” visual layout of OB.

So I want to confirm: can I hide the address bar in the lower left ? maybe CSS or anthers.

thanks~
![image](https://github.com/user-attachments/assets/04021ef5-9383-404c-92ef-1dba4f629268)

**Comment by pjeby** [comment]
If you have the [Style Settings plugin](obsidian://show-plugin?id=obsidian-style-settings), it will have an option to hide the standalone QE bar.  (It shows up down there by default because you can turn off the tab title bar, and would then have no way to access QE in that case.)

**Comment by HelloMugen** [comment]
> If you have the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings), it will have an option to hide the standalone QE bar. (It shows up down there by default because you can turn off the tab title bar, and would then have no way to access QE in that case.)

Great, perfectly solved my needs

I never knew that the setting UI is in Style Setting. I think this can be put in the homepage  to let more people who have the same confusion know.

thanks~

**Comment by pjeby** [comment]
Second sentence of the *very first paragraph* of the home page is, "If you want to hide QE's default breadcrumbs, you can turn them off using the [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) plugin."
