### ISSUE TITLE
"Browse Vault/Folder" toggle and navigating using Vim bindings

### ISSUE THREAD

**Issue by strangerinusall** [pjeby/quick-explorer#106]
Hi, first I want to say this is really an amazing plugin which makes navigation so much more pleasant.

I have 2 questions:
1. Is there a way to make "Browse Vault" and "Browse Folder" actions a toggle? I think it would be really intuitive if I could just click same action second time to close the menu instead of having to hit ESC.
2. I am using Vim plugin for obsidin so naturally navigating up and down with j and k keys in my notes. I also remapped "Go to next/previous file" in folder to Shift+cmd+j/k for super easy navigation in the explorer. Is there any way to to configure this plugin to go up and down (and maybe even sideways) in the "Browse Vault" and "Browse Folder" menus using j/k keys? For example with Shift modifier otherwise search wouldn't work. For Vim users it would be extremely efficient if it was possible to action "Browse Vault" -> couple of hits of Shift + J to go 2 files down -> shift + L to open the next folder, etc (instead moving the hand to arrow keys).

**Comment by pjeby** [comment]
You can toggle between them with the left and right arrows.  Effectively "browse vault" is browse folder followed by left arrows to reach the root, and vice versa.

As for the vim keys, I've added Mod-hjkl to the 0.2.11 release.  (Ctrl on PC, Cmd on Mac).

**Comment by strangerinusall** [comment]
Apparantly I didn't have latest indeed. Mod-hjkl is simply amazing! 

Regarding my first point, I meant let's say I have Shift+cmd+S mapped to "Browse Vault", it would be sweet to be able to click Shift+cmd+S again to leave the "Browse Vault" view, as opposed to hitting ESC. Anyways, it's a minor thing. Super great plugin, thank you!

**Comment by pjeby** [comment]
Yeah, the toggle thing will have to wait for customizable keyboard mapping.
