### ISSUE TITLE
LOVE quick-explorer, can we get some same functionalities in the search pane?

### ISSUE THREAD

**Issue by zeltak** [pjeby/quick-explorer#109]
Hya

I LOVE quick-explorer so much, been waiting for commands like Quick Explorer: Go to next file in folderfor years!

I have a question. Any chance we can we get some same functionalities in the search pane, ie have the command Quick Explorer: Go to next file in folder work on search results?

![CleanShot 2024-11-23 at 17 09 03@2x](https://github.com/user-attachments/assets/a20c2413-fb4d-4ead-84f1-91dc37d9e71e)

thx so much for considering!

Z

**Comment by pjeby** [comment]
I'm not sure what you mean here.  If you arrow down through those files you can nav to them already, and you can also use the QE commands to do what they do.  So I don't understand what you want that's different from that.  (If you want commands that navigate within the search, that wouldn't be folder navigation, for example.)

**Comment by zeltak** [comment]
thx so much for you quick response @pjeby !

let me try and explain with some short clips :)

so if i do a search and try to use keyboard shorcuts you can see it either fails and focuses on the editing note are and if after many tries using the mouse i can actually focus the search pane it just goes up and down without showing/opening the notes contents:

https://share.cleanshot.com/qv7CH9ZY


as opposed to that with youer epic plugin i can use the binded keys for  `Quick Explorer: Go to next` to go up and done and get the notes to show/open, ie:

https://share.cleanshot.com/11F37T0K

i guess im looking for the same functionality in the search results, does that make sense

thanks again for all your amazing work, this is by far the most useful plugin i discovered this year!!

z

**Comment by pjeby** [comment]
QE isn't going to get "next/previous in search" commands, so I'd suggest using hover previews, either the built in one or Hover Editor.  That approach won't work with the keyboard (at least not yet), but it's better than nothing, and it's what I currently do in order to move through search results or backlinks or anything else.

**Comment by zeltak** [comment]
thx for the link and your consideration!!
