### ISSUE TITLE
Support hiding file names from path

### ISSUE THREAD

**Issue by wenlzhang** [pjeby/quick-explorer#11]
Is it possible to add an option for hiding file names from the path? The reason is that the file name can sometimes overlap with that from the following plugin.
[jplattel/open-note-to-window-title: Small Obsidian plugin that updates the window title with the current open note](https://github.com/jplattel/open-note-to-window-title)

If the file name is disable from the path, one can still navigate to desired locations by choosing the desired folders by changing its parent folder.

For instance, it would be great if `Folder 1/Folder 2/Note A.md` may display as `Folder 1/Folder 2` instead.

**Comment by pjeby** [comment]
You can use CSS to hide the `#quick-explorer .explorable:last-child`, if you want to not show it.  I would suggest hiding it by setting a short max-width and overflow: hidden, so that there is still a spot on the screen for the menu to descend from; it may not work properly otherwise.

**Comment by wenlzhang** [comment]
Thanks for the reply.

Could you be more specific about this? I tried to add the following to my theme CSS file and the CSS file of this plugin, but neither of them worked for me.
```
#quick-explorer.explorable:last-child {
  max-width: 1cm;
  overflow: hidden;
}
```

**Comment by pjeby** [comment]
You need a space before the `.`; try this:

```css
#quick-explorer .explorable:last-child {
    max-width: 1cm;
    overflow: hidden;
    display: inline-flex;
}
```

If you want less of the filename showing, you can use 1em or 1px instead of 1cm.

**Comment by wenlzhang** [comment]
Thanks for the prompt reply! It works like a charm now! I will close this issue now.
