### ISSUE TITLE
The font of the file count is too small. Is there a way to make it larger?

### ISSUE THREAD

**Issue by tyf2018** [pjeby/quick-explorer#12]
The font of the file count is too small. Is there a way to make it larger?
![image](https://user-images.githubusercontent.com/56342788/133953138-a589eb32-f2cf-4186-8392-fb04274c84e2.png)
#### Finally, I want to say that the plugin is great, thank you.

**Comment by pjeby** [comment]
In 0.1.8, I've increased the size to 75% of the regular font size; if you want it any larger than that you'll need to use custom CSS.
