### ISSUE TITLE
Feature request: automatically add icons to the list of folders and files containing certain keywords, and customize the display style

### ISSUE THREAD

**Issue by tyf2018** [pjeby/quick-explorer#14]
Thank you for developing such a great plugin!

As the obsidian core plug-in, the file explorer supports automatically adding icons to the folder and file list containing certain keywords, and customizing the display style, like this:

> .nav-folder-title[data-path*="Test"] .nav-folder-title-content::before {
>     content: "📝" !important;
>     position: relative !important;
>     right: 5px;
> }
> .nav-file-title[data-path*="2021-"] .nav-file-title-content::before {
>     content: "📌" !important;
>     position: relative !important;
>     right: 5px;
> }
> .nav-file-title[data-path*="2021-"  i]{
> 	color: var(--new-file-font);
> 	background-color: var(--new-file-bg);
> 	opacity: 100% !important;
> 	border-radius: 18px;
> 	margin-left: -0.3em;
> }

### The result is similar to this:
![2021-10-03_11-40-00](https://user-images.githubusercontent.com/56342788/135738597-20eb6210-4c15-40d4-9e84-f46c3e69c139.jpg)

Does QE consider supporting similar functions? I will very much look forward to the realization of this feature.

**Comment by pjeby** [comment]
Since these are menu items rather than navigation items, you would use e.g. `.menu-item[data-file-path*="2021-"] .menu-item-title::before`.  You may need to make other changes to your CSS as well.
