### ISSUE TITLE
Feature Request: quick filter

### ISSUE THREAD

**Issue by huyz** [pjeby/quick-explorer#15]
You know how in a lot of IDEs like IntelliJ and vscode, when you have a pop-up list, you can start typing characters and in real-time the list filters down to the matches (characters anywhere in the line, with maybe a preference for the initial character of every word)?

Would be great to have that.

As it is, it's still pretty hard to navigate when I have to hit the down arrow many times.

**Comment by pjeby** [comment]
The list doesn't filter when you type, but it should *navigate* when you type.  Is it not doing so?

**Comment by pjeby** [comment]
It searches in this order:

* Items starting with exact characters all together 
* Items with exact characters all together somewhere in them
* Fuzzy match of known characters

How many notes are in the folder in question?
