### ISSUE TITLE
FR: Move Files without the File Explorer being enabled

### ISSUE THREAD

**Issue by chrisgrieser** [pjeby/quick-explorer#17]
I am actually replacing the core plugin file explorer with the quick explorer and the recent files plugin, and I am pretty happy with it, that I disabled the default file explorer. However, it seems that moving files only works with the file explorer being enabled. Would it be possible to move files without the file explorer?

Or would the amount of work not be justifiable for a feature that basically already exists which I would totally understand. This is only a minor request, as it feels a bit wasteful to me to have the file explorer enabled only to have the option to move a file (via quick explorer, even).

**Comment by pjeby** [comment]
Use the context menu (right click or type a backslash) and select "move".

**Comment by chrisgrieser** [comment]
> Use the context menu (right click or type a backslash) and select "move".

does not appear in the context menu when I have the file explorer disabled it. (it does however re-appear when I re-enable the file explorer)
![Screenshot 2021-10-20 23 02 36](https://user-images.githubusercontent.com/73286100/138171664-44ab4a05-828d-4f32-b357-089d9a99027a.png)

**Comment by chrisgrieser** [comment]
Too bad. 

Nevertheless, thanks for your plugin! It matches so well with the philosophy of my keyboard-only theme, that I added support for it in my theme :)

**Comment by pjeby** [comment]
Hm.  It looks like your theme doesn't support navigating through the folders or seeing where you are, though.  It also disables all of Pane Relief's mouse-based navigation features (drag, hover, open, context menu, etc.).
