### ISSUE TITLE
QuickExplorer Collision / Feature Request

### ISSUE THREAD

**Issue by brimwats** [pjeby/quick-explorer#23]
Quick explorer sometimes collides with titlebar as #20 notes, it can also sometimes conflict with themes that move the statusbar to the titlebar, like sanctum
![image](https://user-images.githubusercontent.com/49103046/143781389-a7afb2a9-bb55-4d1b-962a-f6a3e48e3ca7.png)

I was also thinking that this might be solvable with a setting in for QE to only show current level + 2 or 3 levels higher, and then perhaps a [. . . . .]?

**Comment by pjeby** [comment]
Perhaps you should contact the author(s) of the relevant themes to suggest something be done in the theme, as I'm unlikely to add any settings to QE in the near future, and fixing this seems very theme-dependent.  Alternately, you can use some of the CSS snippets posted in these issues that allow hiding QE items or making them opaque.
