### ISSUE TITLE
Support for other plugins [new features]

### ISSUE THREAD

**Issue by alexinea** [pjeby/quick-explorer#24]
Hope to add support for the integration of Folder Note plugin and Icon Folder plugin.

**Comment by pjeby** [comment]
Quick Explorer supports folder notes of the same type as is supported by the Note Folder Autorename plugin.  Did you have some other strategy in mind?

Regarding folder icons, you can replace them by targeting CSS like this:

```css
.is-qe-folder[data-path="some/folder"] svg.folder {
   // CSS to hide/replace the icon
}
```

And if the Icon Folder plugin wants to support doing this for QE it can certainly do so.  I may at some point add an event to allow other plugins to change the file and folder icons, but that will still require *other* plugins to support that feature.

**Comment by alexinea** [comment]
Thanks for the reply.

Quick Explorer is one of my favorite plug-ins, thank you for your work.
