### ISSUE TITLE
It is recommended to support multiple selection

### ISSUE THREAD

**Issue by Andy-AO** [pjeby/quick-explorer#25]
Sometimes you need to move three files to another folder, If there is no multi selection function, the operation will be cumbersome.

**Comment by pjeby** [comment]
Obsidian doesn't actually have any mechanism for applying operations to multiple files, apart from drag and drop in the builtin file explorer.  And I also don't have any idea what the UI for selecting multiple items would look like in QE.  (For example, selecting items from more than one folder would be impossible.)  So I don't see this as being practical at the present time
