### ISSUE TITLE
Feature request: "Create note" in current directory

### ISSUE THREAD

**Issue by chris-lesage** [pjeby/quick-explorer#27]
Hi, I have a suggestion for a feature. It would be very nice to be able to have an additional \ command, **"Create note here"** when navigating the hierarchy with the keyboard. And then the note would be created in that folder. Independently overriding any Obsidian setting for "Default location for new notes".

**Comment by atimeofday** [comment]
> Hi, I have a suggestion for a feature. It would be very nice to be able to have an additional command, **"Create note here"** when navigating the hierarchy with the keyboard. And then the note would be created in that folder. Independently overriding any Obsidian setting for "Default location for new notes".

I second this.

**Comment by pjeby** [comment]
The current keyboard sequence to create a note in the current folder you're browsing is Left, Backslash, Down, Enter.  The Left arrow selects the current containing folder, so you can then perform any menu operations on it that you like.  "New Note" is the first item in the context menu, and should always create an item in the selected folder regardless of the default note location setting.

**Comment by chris-lesage** [comment]
Oh! Pardon me, yeah that totally works. I had tested it just before posting this, and it had put it in my default folder. I must have slipped up on where the focus was. Sloppy testing on my part. Thanks!
