### ISSUE TITLE
Color is not visible in light mode

### ISSUE THREAD

**Issue by Archie-2021** [pjeby/quick-explorer#29]
![image](https://user-images.githubusercontent.com/85870778/147854319-60f3f834-878a-4686-a06b-493971d1c21a.png)
 i am using Minimal theme, but i guess it is not the main issue

**Comment by pjeby** [comment]
It's quite visible for me with minimal in light mode with the default settings.  Perhaps you've changed something in the settings?  Your colors are quite different from the ones showing on my screen, both for quick-explorer and pane-relief.  Mine show a darker text font, your font is white.

**Comment by Archie-2021** [comment]
> It's quite visible for me with minimal in light mode with the default settings. Perhaps you've changed something in the settings? Your colors are quite different from the ones showing on my screen, both for quick-explorer and pane-relief. Mine show a darker text font, your font is white.

yes i changed some stuff in setting and added some css too, but i copied setting from other people and it was a longtime ago. do have any suggestion to where to look to fix this?

I also use Show current file path plugin which shows a similar thing in bottom windows bar and it has not problem:

![image](https://user-images.githubusercontent.com/85870778/147866776-7dd378a4-7c79-41e5-8099-678117fb2d41.png)

**Comment by pjeby** [comment]
I would check if there is an option to reset the defaults, and disable the CSS snippets.  I'd also look for any place where you've set a light font color.   You could also use the Chrome inspector functions to identify the exact CSS rule being used to set the color for those elements, and then find that rule in the CSS snippets or see what variable is being used to configure in the theme settings.
