### ISSUE TITLE
A keyboard binding to navigate to the parent foldernote of the active file.

### ISSUE THREAD

**Issue by kishorekumarxyz** [pjeby/quick-explorer#30]
Much similar to **Navigate Back** and **Navigate Front** commands available by default. Can you kindly provide a command to  **Navigate to the Parent** (or Navigate up)?

**Comment by pjeby** [comment]
QE doesn't have "navigate back" or "navigate front" commands, so I'm not sure what you're saying.  If you want to explore the active file's folder, you can use the "browse current folder", and if you want to go to the parent folder from there you can use the left arrow key.  The left arrow navigates up a folder when Quick Explorer is active.

**Comment by pjeby** [comment]
Closing due to no reply.
