### ISSUE TITLE
[Share+Question] QE + Shell Commands for File Management

### ISSUE THREAD

**Issue by FelipeRearden** [pjeby/quick-explorer#34]
Hello @pjeby !!!!!

In this post I wanna share with you a new workflow that I recently discovered for File Management using QE and the Shell Commands Plugin and ask you a question about some issue that I found when implementing this workflow. 

## Share 

The latest two version of SC has a new feature that let's the user apply Shell Commands only to certain types of "objects" in Obsidian. Two examples are *Files* and _Folders_ using the Context Menu (mouse right click) on the File Explorer Panel. These Features are called _Events_ !
- These new commands will only be visible based on settings `File Menu` and/or `Folder Menu`

In other words, I can create Shell Commands that will only be  available at the File Explorer Pane and only with my focus in on a Folder or a File. 

The real magic is that there are new variables in SC that are specific to create shell commands when I am performing these Events. 

Few examples above and more [here](https://publish.obsidian.md/shellcommands/Events/File+menu#Variables):
- `{{event_folder_path:relative}}`
- `{{event_title}}`

This way I can create a bunch of shell commands applied to file Management that are not native in Obsidian like: 
- Duplicate Folders and Files
- Move folder  
- ...

Since I don't use File Explorer and  I 💙 QE my first instinct was to test if I can applied the fundamentals that I wrote above in QE. And thanks to the way fantastic that Taitava create this new features I COULD APPLY THIS IN QE !!!!!!
- My dream is one day disable File Explorer and do everything with QE (File Management and File Navigation). 

Inside QE If I hit `ALT_ENTER` in a Folder or File, a list of Shell tailored by me will appear and works great ! (Image below)

I wanna share this with you because in my limited mind this is a big integration between two amazing plugins  that could open a big list of possibilities of new workflows to do with QE :)

## My Question 

There is one tiny thing that I wanna check with you about this new workflow between QE and SC. 

I'm gonna use an example and use my poor English to try to explain to you .... 

I have a shell command to duplicate a folder in the same directory . 

`XCOPY {{event_folder_path:absolute}}\* {{event_folder_path:absolute}}_1.md`

its works great, but the QE list in not automatically  updated with new item (folder) in the list 
- Which is absolutely normal because QE made to duplicate folders :)

I let the File Explorer Open in the right just to show you the behavior on the FE panel (sorry for the mess, its my test vault)

![QE1](https://user-images.githubusercontent.com/85180696/157669629-7925a49d-975c-4a2f-8079-b2de34129d89.png)

![qe2](https://user-images.githubusercontent.com/85180696/157669636-14910af9-32e7-4143-87f1-1e27cbdf6ee7.png)

One single Arrow Key Left -> Arrow Key Right and my list in now updated!

![qe3](https://user-images.githubusercontent.com/85180696/157669687-b9c8169b-ed84-4bc0-aed7-ede9de256193.png)

*My Question* is it possible to have a new command that manually updates the QE list ? `QE: Update List`
- In my I'm thinking about using Advanced URI to create a URI command to insert this in the shell command 
- OR use URI + QuickAdd + SC to Create a MACRO command ... something like that 

Another idea could be use URI feature that we were talking about [here](https://github.com/pjeby/quick-explorer/issues/31#issuecomment-1019494855) 

---

Thank for taking your time to read this !!!!

Have  a great day!!!

**Comment by pjeby** [comment]
The issue here was that QE didn't monitor file/folder creation, only renames and deletes.  Version 0.1.13 should now detect when new files or folders have been created (even by shell commands), and update itself automatically.  Let me know if there is still any problem after you update.

**Comment by FelipeRearden** [comment]
> The issue here was that QE didn't monitor file/folder creation, only renames and deletes.  Version 0.1.13 should now detect when new files or folders have been created (even by shell commands), and update itself automatically.  Let me know if there is still any problem after you update.

Thank very much for new release @pjeby !!!!!

Working perfect on version 0.1.13 - Obsidian 0.13.23 - Windows 7
- Using SC for Creating Files
- Using SC for creating Folders
