### ISSUE TITLE
Support "Icon Folder" plugin

### ISSUE THREAD

**Issue by AiurArtanis** [pjeby/quick-explorer#36]
@pjeby 

---

## Request

folder with an icon shows in default file explorer like this:
![image](https://user-images.githubusercontent.com/98091664/158751182-7dcbf2b0-680a-426f-83f9-8f4c2b781cd2.png)

and shows in **Quick Explorer** like this:
![image](https://user-images.githubusercontent.com/98091664/158751276-ec185f43-9084-42fa-bd88-c770f3d6626f.png)

## Environment

OS: win 10
Ob: v0.13.33
Quick Explorer: 0.1.14

## Last

hope for your reply 😁

**Comment by pjeby** [comment]
Technically, this sounds like something the Icon Folder plugin would have to add to QE, not the other way around.  If they need me to add an event or something they can use to integrate, I can do that.

In practice though, as discussed in issue #14, you can use CSS rules to style folders according to their path, and that may be a viable route for the Icon Folder plugin to use, or you can personally set up a CSS snippet instead.

**Comment by AiurArtanis** [comment]
> this sounds like something the Icon Folder plugin would have to add to QE

got it, and i commit an issue related on Icon Folder
[#46](https://github.com/FlorianWoelki/obsidian-icon-folder/issues/46)

**Comment by pjeby** [comment]
I've updated that issue with some info on how the author can support this.  Since there's nothing that can be done on this end I'm going ahead and closing this issue; if the other author needs help they can reply to me via the issue on the icon folder plugin.
