### ISSUE TITLE
[Feature Request] QE+HE Keyboard Hotkey 

### ISSUE THREAD

**Issue by FelipeRearden** [pjeby/quick-explorer#38]
Hello @pjeby !!!!!

I'm starting to use QE+HE and I think I have a suggestion that will be a great addition to QE :)

As far as I know we these are the main keyboard hotkeys shortcuts for navigation inside QE:

`ENTER` -> Open Note
`CRTL+ENTER` -> Open Note in a new Tab
`ALT+ENTER` -> Open Menu Context 

My FR is to add a new hotkey to open the note in HE
- I'm thinking about `CTRL+SHIFT+ENTER` -> Open Note in Hover Editor

I'm aware that we have `Open in Hover Editor` inside the Menu Context `(ALT+ENTER)` but in my humble opinion, we could have a dedicated hotkey for HE 

---

Thanks for reading this !!!!!

Have a great day!

**Comment by pjeby** [comment]
The right arrow will pin the open hover editor, set it to source mode, and make it the active pane.

**Comment by FelipeRearden** [comment]
Forgive @pjeby I forgot to mention one thing...

I was talking about the scenario that I don't have a popover HE previously open.

Example: I have only NoteA.md open in the workspace and I want to open NoteB.md in a new popover using QE. 

My idea was to avoid ALT+ENTER and use a new direct hotkey to open a new HE from QE. 

Is right arrow able to do this ? Maybe I'm missing something:)

**Comment by pjeby** [comment]
If you arrow to (or hover) Note B in QE, a popover should appear to the right; pressing the right arrow closes QE and pins the popover, putting it in source mode and activating it.  (Make sure you have the latest QE and HE - there was a version combination a few days ago where this did not work.)

**Comment by FelipeRearden** [comment]
@pjeby do you have page preview ON on your end ?

**Comment by FelipeRearden** [comment]
> (Make sure you have the latest QE and HE - there was a version combination a few days ago where this did not work.)

Both on latest version: 0.8.7 and 1.21 thanks for the reminder.

> If you arrow to (or hover) Note B in QE, a popover should appear to the right; pressing the right arrow closes QE and pins the popover, putting it in source mode and activating it. 

Working exactly as you said when Page Preview core plugin is ON.

Now I understand why I wasn't having the same experience as you. 


---

Let me just share my workflow and then you judge if is a good addition to QE or not (feel free to close this FR)

Since I don't use Page Preview if possible would be great if I can open a new note in Hover Editor from QE using a hotkey like CRTL+SHIFT+ENTER

---

Sorry for the messy FR this time. QE+HE is something new to me and I never used QE with Page Preview because I always know what is inside the note that I am about to open with QE.
- Few minutes using QE+HE and my muscle memory was asking for a hotkey to open HE the same way that I use CRTL+ENTER to open a note in a new Tab :)

**Comment by pjeby** [comment]
In that case I recommend the sequence backslash-V-R-enter (assuming you have no conflicting context menu items).  Currently Hover Editor does not have an official API for opening hover popovers and there isn't any way to for QE to open one except via the menu items or commands -- and those don't provide any way for QE to actually access the popover.  It's only able to provide the right-arrow function if the popover is loaded for previewing.

**Comment by FelipeRearden** [comment]
Thank you very much @pjeby for the recommendation !

In gonna use this combination as mentioned :)

let's wait for a possible API in the future
- thank for explaining this to me. I didn't know that we need an API and makes all sense.

Feel absolutely free to close this issue or keep open to avoid people creating new FR for the same issue :)

---

Thanks again for your patience :)

**Comment by pjeby** [comment]
I'm going to close because I don't plan to add another hotkey.  If at some point it is possible to open a popover by API, I may change the right-arrow so it will do that if there is not a popover already open.  But there will not be two separate hotkeys for this same action.

**Comment by FelipeRearden** [comment]
Okay @pjeby !
