### ISSUE TITLE
Folder Note Naming Scheme

### ISSUE THREAD

**Issue by ndharari** [pjeby/quick-explorer#39]
Hi, sorry to bother. I have all my vault organized so that my folder notes are named "_FolderName". I really don't want the folder and the note to have the same name (mainly because in this way I know which note is an index note)

Do you know if I can integrate this with your plugin?

**Comment by pjeby** [comment]
Not at the moment, no.

However, if you remove the `_`, you will find that QE places that note at the top of the list *in a separate section*, so you always know which note the index note is.  This is also compatible with the [Note Folder Autorename plugin](https://obsidian.md/plugins?id=note-folder-autorename), and most other folder note plugins will support that naming scheme as well.  (Don't know if any will put the folder note at the top of the regular file explorer, though.)
