### ISSUE TITLE
Feature Request: Persisting the Hover Editor preview when click into the Hover preview

### ISSUE THREAD

**Issue by nhan000** [pjeby/quick-explorer#43]
When I need to edit a note in the Hover Editor preview I need to click the Pin icon ![image](https://user-images.githubusercontent.com/85216095/179230250-6ded7bd8-893b-4c19-b1a3-f04efa59cc26.png) for the Hover Preview to persist, otherwise when I click into the window to edit the note the Hover Preview will disappear.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/85216095/179230217-e6155ba8-33ce-4e81-8ead-57b832d49792.png">

This is not the case for the Hover Editor used in the body of a note where it persist for editing without having to pin the preview window first.

**Comment by pjeby** [comment]
Have you tried using the right arrow key (keyboard) to enter the note instead?

**Comment by nhan000** [comment]
Thanks I didn't know that. Would you consider supporting mouse as well?

**Comment by pjeby** [comment]
Implemented in 0.1.32.  Enjoy!
