### ISSUE TITLE
[Feature Req.] Option to disable page preview?

### ISSUE THREAD

**Issue by train-con** [pjeby/quick-explorer#44]
Hello, I've very recently installed this plugin and it works just as intended. It makes my workflow less stress inducing, hahah.

However, since I use several css snippets and a custom theme to achieve a certain look in Obsidian, page preview wouldn't be as aesthetically pleasing to look at. It's a bummer since I do like page preview. :/

With that out of the way, having the ability to switch page preview on and off would really be of help in my case.

**Comment by pjeby** [comment]
The tab key turns it off for the duration of your session (i.e., until you close Obsidian).

**Comment by train-con** [comment]
> The tab key turns it off for the duration of your session (i.e., until you close Obsidian).

Thank you.
