### ISSUE TITLE
Broken Title Bar after update

### ISSUE THREAD

**Issue by rawxrawxrawx** [pjeby/quick-explorer#45]
Hi PJ, thanks for the plugin, very usable and slick. However, the latest Obsidian update broke some CSS, i guess? The standard title bar is visible again and it looks like this:

![image](https://user-images.githubusercontent.com/7361076/180618217-223aaa90-81fb-4226-acd2-395d00551d14.png)

**Comment by pjeby** [comment]
This should be fixed with the new 0.1.33 update.  Let me know if there's still a problem.

**Comment by rawxrawxrawx** [comment]
Just updated and its fixed. Thanks!
