### ISSUE TITLE
[Bug] Quick Explorer still collides with buttons on Titlebar

### ISSUE THREAD

**Issue by hustrjh** [pjeby/quick-explorer#48]
# Problem
@pjeby Hi, PJ Eby. I'm confused that QE collides with the buttons which I created by **`customizable page header and title bar`** plugin. I know that the new 0.1.33 version of QE relocates the title to the right.  I appreciate your effort for solving titlebar clashes. Actually my titlebar looks like picture below.
![image](https://user-images.githubusercontent.com/69783980/181018343-6b2a0d9f-4fbb-4bc4-80cf-4843dbad6767.png)

# Suggestion
If QE detects that the current path too long to collide with titlebar or just exceed certain words, QE could shorten the path like file explorer with **`...`** symbol. Also it's better to make the function configurable.

P.S. I'm on Obsidian 0.15.6, and QE on 0.1.35. Thanks for your excellent work!

**Comment by pjeby** [comment]
What version of CPHATB are you using?  I can't repro the problem with its 4.6.2 and Obsidian 0.15.8.

**Comment by hustrjh** [comment]
I'm also on 4.6.2.
![image](https://user-images.githubusercontent.com/69783980/181135091-9ad762cd-05cd-4090-8c98-b506235aaf8a.png)

I also made several buttons at **`Left sidebar`**.
![image](https://user-images.githubusercontent.com/69783980/181135180-0fc92937-1b10-45c8-b295-e4f34dfbb83a.png)

**Comment by hustrjh** [comment]
> You can change the order by disabling and re-enabling QE and CPHATB in the order you want them listed.

Thanks a lot for your suggestion. I got it. I'm using the Blue topaz theme and I can hide the centle title with **`style setting`** plugin for the theme.
