### ISSUE TITLE
Can you not display the version number of the OB?

### ISSUE THREAD

**Issue by chenxin0397** [pjeby/quick-explorer#49]
Can't display the version number of OB?
As long as the latest version of this plugin is opened, the version number of the OB will be displayed. I have set it to not show before because of conflicts with my other plugins.
![image](https://user-images.githubusercontent.com/73974352/181037410-bc0714b0-37a1-4c6c-8aec-a2276c520e27.png)

**Comment by pjeby** [comment]
When you say you "set it to not show before", what plugin are you using to do that?

**Comment by pjeby** [comment]
I'm going to guess that you were using minimal or a similar theme or CSS snippet to remove the version info; there was an issue in the current QE that could put it back even if it was hidden by a plugin, theme or snippet.  Please try updating to QE 0.1.36 and see if that fixes the issue.

**Comment by chenxin0397** [comment]
Yes, you're right, it's not a plugin, it's a theme called blue topaz. Thanks for the update, now the problem is solved
