### ISSUE TITLE
FR: Display the contents of the root folder when clicking on '/'

### ISSUE THREAD

**Issue by VKondakoff** [pjeby/quick-explorer#5]
Hello!

Just testing the QE. Here is a question/feature request: why nothing happens when there are no notes open and you are clicking on '/'? I'm pretty sure the contents of the root of the vault should be displayed. 
<img width="764" alt="Снимок экрана 2021-09-03 в 11 49 11" src="https://user-images.githubusercontent.com/230824/131978875-4f2b3ebb-576d-41ea-b48a-c67773a8e1cb.png">
What do you think? (macOS, Obsd 0.12.15, QE 0.1.2)

**Comment by pjeby** [comment]
Thanks for reporting this!  It's fixed in 0.1.3.
