### ISSUE TITLE
the title of the repository will automatically move to the right corner when this plugin is installed in obsidian v0.15.8 with blue topaz theme

### ISSUE THREAD

**Issue by Xieleilab** [pjeby/quick-explorer#51]
the title of the repository will automatically move to the right corner when this plugin is installed in obsidian v0.15.8 with blue topaz theme

**Comment by pjeby** [comment]
That is what it's designed to do, yes.  Did you want it to do something different?  If so, what did you want it to do?  Be invisible, go in the middle, or something else?

**Comment by Xieleilab** [comment]
i want it to be in the middle,for the reason that another plugin named "custom frame" will set a anumber of icons in the right corner of the title bar.
![image](https://user-images.githubusercontent.com/78771561/181661041-87aca82c-c6bf-45ed-b57d-80553f420c2b.png)

**Comment by pjeby** [comment]
Does the theme offer an option to disable it altogether?

**Comment by Xieleilab** [comment]
perhaps not ,  so maybe this plugin can add an option to let users choose their desired position for display

**Comment by pjeby** [comment]
In QE 0.1.38, you can now use the Style Settings plugin to control this: in Style Settings, look for the Quick Explorer section and make the changes there.
