### ISSUE TITLE
Bug in v0.16.0 with top bar

### ISSUE THREAD

**Issue by Amparose** [pjeby/quick-explorer#52]
When Quick Explorer is enabled it adds padding to the top of the Obsidian window. Happens in Default theme and others.

**Comment by pjeby** [comment]
What OS are you on, and what Appearance settings are you using for the titlebar?  (A screenshot would also be nice, since I'm not seeing a problem on my end.)

**Comment by trainbuffer** [comment]
Maybe this? I don't see Quick Explorer at all. Also, I can't grab with the mouse in the whole top area (to the right of the stoplights) to move the window. 

macOS, Obsidian 0.16.1, default theme, only Quick Explorer plugin enabled.

[img]https://ibb.co/CnJZScd[/img]
[img]https://ibb.co/rGbBZfH[/img]

**Comment by trainbuffer** [comment]
It's just being sneaky. Hotkey brings it up albeit in the wrong spot. :D 
![3](https://user-images.githubusercontent.com/3751726/187808882-3840d4f5-1fd1-4e84-acbb-8d26217a7d89.png)

**Comment by pjeby** [comment]
You need to change "Window frame style" to "Obsidian" if you want to be able to see it.  The new default "hidden" mode hides the titlebar, and Quick Explorer with it.

**Comment by trainbuffer** [comment]
Yeah, I tried all three Window frame styles because I thought I was missing something. This is what I see with "Obsidian frame" Window style. 

![Screen Shot 2022-09-01 at 10 04 51](https://user-images.githubusercontent.com/3751726/187810409-9f3a8b3f-3476-4ab4-bc5c-0b92d60c7415.png)

**Comment by pjeby** [comment]
How odd.  Maybe it's this issue then:  https://github.com/pjeby/pane-relief/issues/29 -- try the CSS from that and see if it fixes the issue.  (The titlebar button container that contains the history buttons and QE has some styling issues on Mac that the CSS in that other issue fixed for the other person reporting a problem with Pane Relief.)

**Comment by trainbuffer** [comment]
Here's a vid. Will try the css snippet. 

Thanks for your hard work; seems rough seas ahead for the short term.

**Comment by trainbuffer** [comment]
The CSS works perfectly! 😙👌 Thanks again.

![Screen Shot 2022-09-01 at 10 50 02](https://user-images.githubusercontent.com/3751726/187814513-5b457ef2-bf38-44fb-8f68-1c3fa9ee7755.png)

**Comment by pjeby** [comment]
It looks like the Obsidian devs will be fixing this in 0.16.2, not sure when it will drop.  In the meantime, you can continue using the CSS.

(When they were setting up the new theme, it somehow got left as a block display on Macs even though every other platform has `flex` for that element.  I didn't see any problems during the alpha because I'm not on Mac.)

**Comment by trainbuffer** [comment]
Slightly off topic, but with the Window Pane Style set to Obsidian, I get my vault name and Obsidian version looming large and **BOLD** off to the right. I'd like to get rid of that. Is this too part of the titlebar button container? I looked in the dev console but couldn't suss out where this comes from. 

![Screen Shot 2022-09-01 at 13 38 04](https://user-images.githubusercontent.com/3751726/187832421-d410d441-001e-46e7-a393-97b1c968b170.png)

**Comment by pjeby** [comment]
If you want to get rid of the center text entirely, you can use the Style Settings plugin and go into Quick Explorer and set "Obsidian Title" to "Hide it entirely".

If you want to change the font settings or other CSS styling, you're looking for `.titlebar .titlebar-text`.

**Comment by trainbuffer** [comment]
Thanks again. 🙏🏼 I'll have a poke around.

**Comment by Amparose** [comment]
Sorry for the lacking first post. Indeed, I'm using MacOS 11.6 or 12.x and Obsidian v0.16.1. _Window frame style_ is **Hidden (default)** and even with that CSS snippet I get the broken top bar and Quick Explorer appears under the headlights ([as posted above](https://github.com/pjeby/quick-explorer/issues/52#issuecomment-1233598699)). I always have had top bar hidden via Hider plugin and evoke QE with keyboard.

![Screen Shot 2022-09-01 at 11 52 13](https://user-images.githubusercontent.com/949192/187890573-5e21dfc0-82e5-47a3-a3e3-8596f2d26502.png)

I'm using Minimal theme in this screenshot but it's same issue in Default.

I can't inspect any element that is pushing things down but something is causing the body 30px top padding to push itself down:

```css
body.is-frameless.is-hidden-frameless {
    padding-top: 30px!important;
}
```

Overriding that to `0px` fixes the issue for me but not sure what the cost is as this seems to be an Obsidian rule not a plugin (might break something else?):

![CleanShot 2022-09-01 at 12 14 01](https://user-images.githubusercontent.com/949192/187890666-6a153316-5bcc-4ea5-a816-14822f04eb7b.png)

However, when the Obsidian is unfocused I get this ugly artefact corresponding to top margin of the ribbon:

![CleanShot 2022-09-01 at 12 14 11](https://user-images.githubusercontent.com/949192/187890835-ce8f5414-a436-4eec-aa7a-eb1c5f075b94.png)

**Comment by pjeby** [comment]
I've pushed a new version of QE that should fix part of this issue.  The other part is fixed in Obsidian 0.16.2 alpha, which should be available as an insider release soon.

**Comment by Amparose** [comment]
I just got Obsidian 0.16.2 and with _Window frame style_ set to _Hidden_ Quick Explorer 0.1.40 still has this bug. Overriding with the CSS i suggested above patches it:

```css
body.is-frameless.is-hidden-frameless {
  padding-top: 0px!important;
}
```

I haven't yet run into problems caused by this snippet but don't consider this "the solution".

**Comment by pjeby** [comment]
To resolve this, I've moved QE to the left of the status bar when Obsidian 0.16 is in Hidden or Native frame modes, and removed the erroneous padding rule.  Sorry for the inconvenience.
