### ISSUE TITLE
Add a setting to hide status bar breadcrumbs

### ISSUE THREAD

**Issue by pcuellar** [pjeby/quick-explorer#54]
First of all, thanks for developing this plugin, it makes a great difference when navigating folder trees. 

Because I have my ‘title bar’ disabled, QE is sitting at the bottom left of the status bar. Since I use the 'Hider' plugin to hide the app ribbon, it makes it so that QE's breadcrumbs bar ends up under the app ribbon upon hovering (Hider makes the ribbon appear on hover at the bottom left of the window). Additionally, QE elongates the status bar into the main window resulting in less reading area at the bottom. My suggestion would be to have an option that disables the breadcrumbs bar (especially now that you can get persistent breadcrumbs through activating ‘tab title bar’), while still allowing you to trigger the floating folder. 

I use v.0.16.3 with Minimal and 'hidden' window style frame.

**Comment by pjeby** [comment]
This will be added to the style settings in the next release, along with support for using the 0.16.3 title bar breadcrumbs to access QE menus.

**Comment by pjeby** [comment]
0.2.0 is now out with this feature and if you turn off the status bar crumbs it will use the tab titlebar ones if they are visible for the active pane.

**Comment by pcuellar** [comment]
This is brilliant, thank you so much! I noticed that if you choose the setting to hide QE the explorer shows up in the middle of the screen as opposed to on the left (see screenshot). I was able to correct that with a CSS snippet (see below) but was wandering if there is a more elegant way. 

Snippet
`div.menu.qe-popup-menu {
  left:  9.688px !important;
  top:  52px !important;
}`

<img width="1520" alt="Screen Shot 2022-09-25 at 6 26 34 PM" src="https://user-images.githubusercontent.com/20482146/192168341-67dfc876-de2f-478f-b496-8db5c374a946.png">

**Comment by pjeby** [comment]
I guess you're not currently showing the tab title bar?  The new mode is intended to work with the tab title bar. (Settings > Appearance > Advanced > Show tab title bar).

**Comment by pcuellar** [comment]
I do have it on, it's behind QE's explorer. This note is on root, that's why you can't see the path. I tried disabling the title bar and then QE's explorer shows on the left. Is as if it was linked to the title bar.

**Comment by pjeby** [comment]
Yes, that's how it works if you don't have the status bar or main title bar available.  QE uses its own breadcrumbs first (if visible), or else the breadcrumbs in the title bar of the active tab.

That does mean that it will tend to end up in the middle of the screen, if you only have one tab group and don't align the header breadcrumbs to the left.  (Obsidian centers them by default.)

**Comment by pcuellar** [comment]
Gotcha! Thanks for the explanation.
