### ISSUE TITLE
A command with hotkey to go up one level in folder hierarchy

### ISSUE THREAD

**Issue by Archie-2021** [pjeby/quick-explorer#56]
There are already commands for going to next/previous file in the folder, adding one to go up on level (to the first file in the folder maybe) would make it possible to just navigate the folders without need to any links or mouse which can be really handy. 

Thank you

**Comment by Archie-2021** [comment]
> 

Correct, tbh now that you said it like that I see that it maybe not worth the effort of giving it a new hotkey and remembering it.

One other issue I just found is that using (menu key, the one between right super and ctrl key) don't work when browsing the file system on your plugin. just want to check to see if it is something on my end or something related to the plugin. This plugin is perfect for a all keyboard workflow but the only major issue is that I can't do stuff on the note using the commands on the right click menu.

**Comment by pjeby** [comment]
Backslash (or alt-enter) opens the context menu for the current item.

**Comment by Archie-2021** [comment]
> Backslash (or alt-enter) opens the context menu for the current item.

Thank you very much

**Comment by pjeby** [comment]
Support for the context menu key will also be added in the next update.

**Comment by Archie-2021** [comment]
> Support for the context menu key will also be added in the next update.

I think adding support for Ctrl-n and Ctrl-p for navigation would be nice to.
