### ISSUE TITLE
Page preview in quick explorer blocks quick explorer itself

### ISSUE THREAD

**Issue by Ali-C-Ila** [pjeby/quick-explorer#57]
## Problem and usecase
When using quick explorer, there seems to be no option to turn off "page preview on hovering", which will block quick explorer itself and render it unusable in more narrow windows.
( I tried turning on all "require Ctrl/Cmd to preview" options, but none of them works.) 

![image](https://user-images.githubusercontent.com/56729449/195744618-1d64af1e-6a8b-4630-bebd-8f85dc4d97d1.png)

## proposed solution
1. Better placing of the preview window so that it doesn't block the file path bar.(Possibly even shrink it to fit the size)
2. Option to turn on "require Ctrl/Cmd to preview".

## current workarounds
1. Don't use the plugin when thewindow is narrow.
2. Completely turn off the Page Preview plugin. (But that is insufferable for me.)

**Comment by pjeby** [comment]
The "Tab" key toggles the previews on or off.  If you turn it off, it will remain off until the next Obsidian restart or plugin update/re-enable.
