### ISSUE TITLE
This plugin is not compatible with "Hover editor" plugin 

### ISSUE THREAD

**Issue by ribber** [pjeby/quick-explorer#60]
I both install this pugin and  Hover editor plugin. When I use direction key to navigate my note，the preview will flash. And
 Sometime press direction key can't move the focus. an option disable preview maybe useful

**Comment by pjeby** [comment]
1. There is currently an issue where if you have the mouse cursor over the menu or the area where the popover appears, this problem will happen.  If you move the mouse cursor away to another part of the screen and navigate by keyboard, it works around the issue.
2. You can disable the preview with the Tab key.

**Comment by ribber** [comment]
OK，Thank you very much

**Comment by pjeby** [comment]
Version 0.2.4 now has a fix for the issue where the selection jumps if a long menu/folder scrolls while the mouse is over part of it.  Please let me know if that fixes this for you.

**Comment by ribber** [comment]
I have a try，and this problem did not happen.  The issue is fixed，Thank you very much

**Comment by XMB-7** [comment]
This issue seems still not addressed properly.
![Obsidian_oSbGM1wOOR](https://user-images.githubusercontent.com/65625632/205208454-27f947df-df02-4d5d-bc1a-4a248dbfc67c.gif)

The current workaround I found is like below.
![Obsidian_9u5fZdFoI6](https://user-images.githubusercontent.com/65625632/205208587-acea4c0b-a4cc-40dc-9d05-8e3221d16ca9.gif)

**Comment by pjeby** [comment]
If you click the hover editor once before dragging, it won't close.  I will however attempt to address this (new) issue in the next release.

**Comment by pjeby** [comment]
Ok, 0.2.7 now allows dragging the hover editor without needing to click in its body first.
