### ISSUE TITLE
Add an option to not showing content of the files automatically

### ISSUE THREAD

**Issue by Archie-2021** [pjeby/quick-explorer#62]
Add an option to quick explore without triggering preview and activating and deactivating it manually. It is nice to be be able to explore in files sometimes and in small window sizes it is not possible. You can add a separate option for it to start with active preview or not in case some people doesn't like it.

Thank you very much.

**Comment by pjeby** [comment]
The tab key disables previewing, and its setting remains in effect while Obsidian is open.  I do not anticipate adding a setting for this any time soon.

**Comment by Archie-2021** [comment]
> The tab key disables previewing, and its setting remains in effect while Obsidian is open. I do not anticipate adding a setting for this any time soon.

Cool, that is good enough for me. Please add some documenttion for hotkeys on this plugin. They are great but how we should know they exist?

**Comment by pjeby** [comment]
It's in the README - see the section that says, "And an extensive set of keyboard operations is available as well:"

**Comment by Archie-2021** [comment]
> It's in the README - see the section that says, "And an extensive set of keyboard operations is available as well:"

Sorry I must forgot it has been added. Thank you very much.
