### ISSUE TITLE
File Name Search includes the number of files inside a folder in the search.

### ISSUE THREAD

**Issue by talenelat-elin** [pjeby/quick-explorer#63]
When using keyboard-search to select an item, (Opening the quick-explorer, then using alphanumerical keys directly to set the highlight/focus on a file or folder) it includes the number of files inside a subfolder in the search string.
An example, tested in the sandbox vault with no other plugins installed:

![image](https://user-images.githubusercontent.com/71895835/200277879-0891c958-d748-4531-83d8-d88f8bd90f9a.png)

Pressing the keyboard shortcut to show quick explorer shows this, but after that, pressing `3` does not highlight `03 Guides`, as expected, it instead highlights `01 Adventurer` which has three files inside it. 

If I delete or move files in `01 Adventurer` so that it (or any other folder) doesn't have 3 files anymore, pressing `3` will then highlight `03 Guides` as expected.

<details><summary>Debug Info</summary>

```
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.0
	Operating system: Windows 10 Enterprise 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Quick Explorer v0.2.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```
</details>
P.S. Really love your plugin. It + Folder Note are the major reason I decided to stay in Obsidian instead of Dendron!

**Comment by pjeby** [comment]
A fix for this has been released as QE version 0.2.3.  Let me know if any problems remain.
