### ISSUE TITLE
Chose status or title bar?

### ISSUE THREAD

**Issue by kikollan** [pjeby/quick-explorer#64]
First of all, thanks for the plugin. I really like to be able to navigate folder with the keyboard. Now, my question: is there any way to choose if QE shows at the title bar or the status bar? It appears in status for me, but I have seen some screen captures with it showing at the title bar.

Thanks again!

**Comment by pjeby** [comment]
In Settings > Appearance > Advanced, set the "Window frame style" to "Obsidian frame".  Otherwise there's no title bar there for it to show in.

**Comment by kikollan** [comment]
Nice! Thanks :)
