### ISSUE TITLE
[FR] button for previous and next file in folder

### ISSUE THREAD

**Issue by hannesdelbeke** [pjeby/quick-explorer#73]
### request
there's a command for going to the next or the previous file in a folder, 
it be great if there also were 2 visible buttons at the bottom of my note.

### concept art
note the 2 buttons at the bottom of my note
![image](https://user-images.githubusercontent.com/3758308/220172674-1c3a398c-2ea6-408a-9c89-325160aa7b38.png)

more detail described [in this obsidian forum post](https://forum.obsidian.md/t/navigate-sibling-page-previous-next/52701)

**Comment by pjeby** [comment]
You can use the Commander plugin or similar plugins to add buttons to the view header for this purpose.  If you want to be able to see what the next/previous files are, you can use the quick explorer hotkey to pop up the list and then arrow up or down as well.

Having them in the document is an interesting idea, but I don't foresee myself spending any time on such a feature in the near future as I do the two things listed above (i.e., either navigate blindly with header buttons from Commander, or pop up QE with the hotkey and arrow up and down with Hover Editor active to page through the notes with pgup/pgdn.)
