### ISSUE TITLE
FR : multiple file selection

### ISSUE THREAD

**Issue by imeed166** [pjeby/quick-explorer#74]
Hi, thank you for this plugin, I've been struggling to use obsidian because of this, but now I can navigate files with the keyboard, thank you.

There is still, however, one last thing, I can't do from your plugin, and that is "multiple file selection" either via holding the `shift` key or the `command` key. If this is implemented, I can toggle the context menu and remove the selected files directly from the keyboard.

What do you think ?

**Comment by pjeby** [comment]
I don't expect to implement that feature any time soon, if at all.  Quick Explorer is basically just a quick hack based on Obsidian menus and doesn't really have any way to do anything with multiple selection.  You may want to investigate whether it's possible with the built-in explorer; I know you can do it with the mouse, and if it can't be done by keyboard you can always request the feature via the Obsidian forums.

**Comment by imeed166** [comment]
Okay, thank you for providing me with alternatives.
