### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by justiceamoh** [pjeby/quick-explorer#75]
Thanks for a great extension! This solves my biggest issue with obsidian by providing a keyboard-driven means of switching between notes. 

The only difficulty I'm having with this extension is the sort order. My notes are sorted by `modified time` so new notes are always on top. It's mentioned in the README that there's currently no way of sorting files in a different manner than alphabetical. Do you plan to support that? Is there a workaround to configure the sorting to modified time?

**Comment by pjeby** [comment]
I don't have any *immediate* plans to support it, no.  It's in the "nice to have someday" list.

You might want to have a look at [Grappling Hook](https://github.com/chrisgrieser/grappling-hook) or other Obsidian plugins, or even use Obsidian's keyboard commands to jump to the explorer pane and then arrow to the next or previous file.

**Comment by justiceamoh** [comment]
Ah got it! Thanks for the prompt response. I'll check out the others then.
