### ISSUE TITLE
Feature Request: Can we have the full path hide from the status bar?

### ISSUE THREAD

**Issue by lethefrost** [pjeby/quick-explorer#77]
Since we already have a path display under the tab title (if you turn the option `Show tab title bar` on in `Appearance` setting) where we can utilize this plugin, I believe there's no need to have duplicate path displays at two place on the screen. 

It would be great if we could have an option to turn off the one in the status bar in the bottom left corner, (or automatically hide that one when the title bar is on) because some other plugins also take many spaces in the status bar. It gets quite crowded, especially when the file name is long or when it gets into a deep folder descended from the root. 

Thank you so much for this plugin! It's awesome!

**Comment by pjeby** [comment]
If you install the Style Settings plugin, it has a toggle in its settings for for that under "Quick Explorer".  The setting is called "Hide Quick Explorer".
