### ISSUE TITLE
FR: Double click to open folder note

### ISSUE THREAD

**Issue by j-maffe** [pjeby/quick-explorer#78]
I wonder if it'd be feasible to allow for double click to open the folder note of the folder clicked on if it exists. Thanks for the awesome plugin! :D

**Comment by pjeby** [comment]
Obsidian (and browsers in general) don't have a standard way to detect double clicks.  But double-Enter will do this from the keyboard, since the folder note gets selected when you enter a folder (unless it's the folder you opened QE from, in which case you need to do Home-Enter).
