### ISSUE TITLE
Low contrast in the minimal theme light version

### ISSUE THREAD

**Issue by dariuszkowalski-com** [pjeby/quick-explorer#8]
It looks like this:
![image](https://user-images.githubusercontent.com/37656900/132328141-3a22e6a2-ad94-4e8b-9113-9ec6a6fa8bd8.png)

**Comment by pjeby** [comment]
I just loaded the latest minimal theme with no other CSS active, and it doesn't look anything like that image (the text is dark and the highlight is bluish, not red).  Try turning off other CSS snippets, or updating to the latest version of the theme (and this plugin).

Alternately, if you're using the minimal theme settings editor -- which is what the red makes it look like -- you probably need to change some of its settings.

**Comment by dariuszkowalski-com** [comment]
the newest version oth theme helps and it looks ok. thx.
