### ISSUE TITLE
[FR] Hide files with extensions from the Excluded files setting in Files & Links

### ISSUE THREAD

**Issue by j-maffe** [pjeby/quick-explorer#82]
So basically if any file would be excluded from the Files sidebar due to being in the Excluded files list in Files & Links setting page, it would also be excluded in Quick Explorer. An obvious case where this would be helpful is for navigating asset folders that contain attached images (note embeds) that clutter other important files like pdfs. I think this would make a natural extension of the settings of the file explorer and would help QE have a more focused view.

Thanks a bunch!

**Comment by pjeby** [comment]
I don't understand how this would work.  QE shows the same files as the built-in explorer does.  That means it already excludes non-standard types (i.e. extensions Obsidian doesn't recognize) if you don't have the option to show all file types on.  But it doesn't exclude "hidden" files for the same reasons the file explorer doesn't.

It sounds like maybe you should be using folder notes?  If you create a folder that's the same name as a note, and move the note and its attachments into that folder, QE makes it very easy to navigate.  You'll see the note at the top of its own folder listing, for example, and when you navigate or hover over a folder with a folder note, the popup will preview the folder note.

There is also a plugin (Note Folder Autorename) you can use to both easily create folder notes, and to automatically move/rename the folder when you move or rename the note.  This keeps the attachments always alongside the note for a seamless workflow.

**Comment by j-maffe** [comment]
My apologies, I think I had a CSS snippet that hides these files with excluded extensions. I really think that it would be better if there's an option to keep them hidden in QE as it sort of acts as a mini-view of file explorer. 
In any case, I think I managed to create a snippet that hides them if anyone else was also looking to hide them
`
div[data-file-path$='.png']{
	display: none !important;
}
`
Thanks a lot for your suggestions!
