### ISSUE TITLE
[Question] Is there any way to show the title of notes on the main title bar when using the plugin?

### ISSUE THREAD

**Issue by lilskippyy** [pjeby/quick-explorer#83]
Hello. 
I would like to be able to show the title of the open note on the main title bar when using quick-explorer. 
Is there any way to do that, either with css or something else?
Currently I can only either show the plugin's bread-crumbs or, using the style plugin, can either hide it completely or just show obsidian name and version. 

Thanks.

**Comment by pjeby** [comment]
You can switch Obsidian to "Native Frame" (under Settings > Appearance > Advanced) and then you will see it in the OS level window titlebar.  (Note that even if you have a different titlebar mode set, the OS-level window title always includes the note name -- you just can't *see* it unless you're using the Native Frame style.)

Depending on what you are trying to accomplish, there are also other options.  Tabs of course show the note name, and you can turn on "inline title" or "tab title bar" both of which are ways to show the note name, often quite prominently.  Tab titlebar includes QE-style breadcrumbs as well, so you can hide QE entirely in such a case.

Can you tell me more about what you're trying to accomplish?

**Comment by lilskippyy** [comment]
Using Native Frame really works for showing the active note name in the main title bar, I didn't know about that thanks!

What I was trying to accomplish is to just show the active note title on the main title bar using the "Obsidian Frame" (didn't know the difference to the native one so far, but thanks again for letting me know lol), while still using the quick explorer plug-in.

It is hard for me to just use the tab title bar for reference, since i often have multiple tabs open and I just can't see the title of each one. Also I use lots of excalidraws, that don't have inline titles and long notes that I would have to always scroll up to see the title. 

Thanks again! Quick explorer is really awesome btw

**Comment by pjeby** [comment]
The tabs are not the same thing as a tab title bar.  You have to turn tab title bars on in the Appearance > Advanced settings to see them.  They go across the entire pane (so they have room for long title) and stay there even if the pane is scrolled, even if you're using Excalidraw.  They were the default way of seeing filenames before Obsidian had tabs or inline titles.

**Comment by lilskippyy** [comment]
Oh okay ! Yeah I have them on but, they only show full paths for files, never only the file name, which was what I wanted to have. My problem is that I mostly use folders for quick organizing thing, also have a tendency to use long folder names so I have a better description of what's going on in there. So I never really get to see the file name itself on the tab bar, only the long trailing path names most of the time. If there was a way to show only file names would be great. I already have the full path at the bottom bar.

**Comment by pjeby** [comment]
You can use a CSS snippet like this to hide the folders unless you're hovering the titlebar:

```css
.view-header:not(:hover) .view-header-title-parent {
   display: none;
}
```

**Comment by lilskippyy** [comment]
> You can use a CSS snippet like this to hide the folders unless you're hovering the titlebar:
> 
> ```css
> .view-header:not(:hover) .view-header-title-parent {
>    display: none;
> }
> ```

Yes! it worked! Thank you so much!
