### ISSUE TITLE
There shouldn't be a leftmost slash when opening new tabs

### ISSUE THREAD

**Issue by nuanjanP** [pjeby/quick-explorer#84]
Hi. First of all, thank you very much for this plugin.

So, this might come off as nitpicking but, I noticed that when I open new tabs, the tab title bar displays as "/ New tab", which while not a fatal problem, the leftmost slash does come off as a bit weird I guess? (Because "New tab" isn't a file.)

Also, the breadcrumb in the status bar in this case displays "/", where nothing at all (an empty string) is perhaps more appropriate.

Thank you in advance. :)

**Comment by pjeby** [comment]
In both cases, the intent is to allow Quick Explorer to be accessed via the mouse.  If there's no slash, there's nothing to click.

**Comment by nuanjanP** [comment]
Oh, my apologies. I just realized that slash can be clicked too. :)
