### ISSUE TITLE
Plugin settings not available

### ISSUE THREAD

**Issue by KrzysiekWu** [pjeby/quick-explorer#88]
In the README file, it is written:
_Like the built-in file explorer, Quick Explorer will either show all files, or only the ones supported by Obsidian, depending upon whether the "Detect all file extensions" setting is enabled in the "Files and Links" options tab._

Unfortunately, the options are not available for the Quick Explorer plugin:
![image](https://github.com/pjeby/quick-explorer/assets/2963024/75710447-9c68-437b-8cf5-c0f9e3dc1c8c)
![image](https://github.com/pjeby/quick-explorer/assets/2963024/e000d228-4b77-4f60-bd6b-11c787589ec1)

**Comment by pjeby** [comment]
As the documentation says, you need to look at

> the "Files and Links" options tab

It's an Obsidian setting, not a QE setting.
