### ISSUE TITLE
Excluded files/folder keeps being displayed

### ISSUE THREAD

**Issue by ivensrocha** [pjeby/quick-explorer#92]
Hello! I started using your plug-in and it's perfect for my need. One thing that I noticed, though, is that it displays all files, even the excluded ones (Files and links settings).

This is my current configuration:
![Screenshot 2024-03-30 at 15 12 13](https://github.com/pjeby/quick-explorer/assets/976430/a4e78ce0-3daa-4ef6-ac6b-60bd7eb1f17a)

This is what is displayed on Obsidian's default file explorer:
![Screenshot 2024-03-30 at 15 14 16](https://github.com/pjeby/quick-explorer/assets/976430/20d79a8e-554e-4f7b-9fa3-43d1f70bcc8b)

And this is what is displayed in Quick Explorer.
![Screenshot 2024-03-30 at 15 12 20](https://github.com/pjeby/quick-explorer/assets/976430/d9df754c-3f01-44b4-a581-ad5c6f9b8b8f)

Maybe it's a bug or maybe I'm doing something wrong?

Cheers!

**Comment by pjeby** [comment]
QE doesn't support exclusions.  TBH I'm not sure why the builtin file explorer is hiding them either - that seems like a bug to me since if you can't search, open, or browse to a folder, why is it in the vault at all?  (That is, how will you edit templates if you can't get to them at all?)

**Comment by ivensrocha** [comment]
Nevermind - it was a third-party plugin called Hide Folders that was doing it. I'll reach out to them to see if they can make that compatible with your plugin. Thanks!

**Comment by pjeby** [comment]
If you don't care about keyboard accessibility, you can style away specific folders like this:

```css
.menu-item.is-qe-folder[data-file-path="path/to/folder"] {display: none !important;}
```

And the same applies to the stock file explorer, actually:

```css
.nav-folder:has(>.nav-folder-title[data-path="path/to/folder"]) { height: 0; overflow: hidden; }
```

In other words, you can (visually) hide folders just using CSS snippets that list the folders you're hiding, without needing a plugin.  But if you use arrow keys to navigate either QE or the file explorer, you're going to select the invisible folders anyway as you arrow down through the list.  (Pretty sure that happens now with the plugin you're using, too.)
