### ISSUE TITLE
Incompatibility with Obsidian 1.7

### ISSUE THREAD

**Issue by Morganwan90** [pjeby/quick-explorer#95]
Obsidian has updated to the beta version 1.7, and I've found that this plugin is not compatible with it.
I've noticed that this plugin has not been updated for a long time, but it is indeed very practical and I hope it can be made compatible with the next version.

**Comment by pjeby** [comment]
Can you be more specific about the incompatibility?

**Comment by pjeby** [comment]
Never mind, I found it.  0.2.9 update has been released with the fix.

**Comment by Morganwan90** [comment]
thanks a lot！
