### ISSUE TITLE
[Bug] Fails to load into Style Settings upon startup

### ISSUE THREAD

**Issue by Ali-C-Ila** [pjeby/quick-explorer#99]
1. After Obsidian restarts, there appears to be no Quick explorer options within the style settings.
![image](https://github.com/user-attachments/assets/ea6e0733-a5ba-4b72-9db1-b5baffe0cbd5)
2. So quick explorer bar is not hidden
![image](https://github.com/user-attachments/assets/187617d3-ec9e-4edc-af73-a6faec2afb62)

3. current workaround
After changing themes manually, style settings will load in the proper options, and the quick explorer bar disappears.
![image](https://github.com/user-attachments/assets/259eeb70-6364-485b-b981-4f03bb06ed12)

## debug info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Blue Topaz v2024042603
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 16
		1: Tag Wrangler v0.6.1
		2: Dataview v0.5.67
		3: Style Settings v1.0.8
		4: Sortable v0.3.1
		5: Settings Search v1.3.10
		6: Quick Switcher++ v4.3.0
		7: Outliner v4.8.1
		8: Obsidian_to_Anki v3.6.0
		9: Multi Tag v0.10.0
		10: Linter v1.24.0
		11: Image Context Menus v1.8.0
		12: Find orphaned files and broken links v1.10.0
		13: Excalidraw v2.2.7
		14: DB Folder v3.5.1
		15: Change Case v2.0.61
		16: Quick Explorer v0.2.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by pjeby** [comment]
Try disabling (and then re-enabling) Style Settings.  It's likely the issue is that QE is loading after Style Settings, and if so then that will fix it.

**Comment by Ali-C-Ila** [comment]
That does fix it!
